# Generated by Django 5.2.4 on 2025-07-16 07:02

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Artist',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(default='new', max_length=255)),
                ('artist_name', models.CharField(max_length=255)),
                ('agency_name', models.CharField(blank=True, max_length=255, null=True)),
                ('website_link', models.URLField(blank=True, max_length=255, null=True)),
                ('date_added', models.DateField(auto_now_add=True)),
                ('date_removed', models.DateField(blank=True, null=True)),
            ],
        ),
    ]
