# Generated by Django 5.1.6 on 2025-07-17 12:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parser_app', '0002_alter_artist_date_added_alter_artist_date_removed_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='artist',
            name='date_added',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='artist',
            name='date_removed',
            field=models.DateField(blank=True, null=True),
        ),
    ]
