# Generated by Django 5.1.6 on 2025-08-09 12:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parser_app', '0004_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='status',
            name='artists_found',
            field=models.IntegerField(null=True),
        ),
    ]
