# Generated by Django 5.1.6 on 2025-08-11 07:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('parser_app', '0005_status_artists_found'),
    ]

    operations = [
        migrations.RenameField(
            model_name='status',
            old_name='artists_found',
            new_name='scraped',
        ),
    ]
