# Generated by Django 5.1.6 on 2025-08-11 07:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parser_app', '0006_rename_artists_found_status_scraped'),
    ]

    operations = [
        migrations.AddField(
            model_name='status',
            name='deleted',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='status',
            name='new',
            field=models.IntegerField(null=True),
        ),
    ]
